# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Dolls"
  pageRef = "dolls"
  weight = 10

#[[main]]
#  name = "Neoma"
#  parent = "Dolls"
#  pageRef = "dolls/neoma"
#  weight = 20

#[[main]]
#  name = "Seacan"
#  parent = "Dolls"
# pageRef = "dolls/seacan"
#  weight = 20

[[main]]
  name = "Sewing Patterns"
  pageRef = "sewing"
  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30

[[main]]
  name = "Visuals"
  pageRef = "visuals/gallery"
  weight = 30

[[main]]
  name = "Photo Gallery"
  parent = "Visuals"
  pageRef = "visuals/gallery"
  weight = 30

[[main]]
  name = "Charts"
  pageRef = "visuals/charts"
  parent = "Visuals"
  weight = 30

[[main]]
  name = "AI Edits"
  pageRef = "visuals/ai"
  parent = "Visuals"
  weight = 31

[[main]]
  name = "Timeline"
  pageRef = "visuals/timeline"
  parent = "Visuals"
  weight = 30

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 90

[[main]]
  name = "About"
  pageRef = "about"
  weight = 100

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/halcyonstraits"
  weight = 200

[[main]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://youtube.com/HalcyonStraits"
  weight = 300


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
